version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: faculty-system
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
